version = 0.1

[default.deploy.parameters]
stack_name = "xray-sam"
resolve_s3 = true
s3_prefix = "xray-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "TargetUrl=\"https://jsonplaceholder.typicode.com/todos/1\""
image_repositories = []
